<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST');
header('Access-Control-Allow-Headers: Content-Type');

$dataFile = '../data/menu.json';

function getMenu()
{
    global $dataFile;
    if (!file_exists($dataFile)) {
        return [];
    }
    $json = file_get_contents($dataFile);
    return json_decode($json, true) ?: [];
}

function saveMenu($menu)
{
    global $dataFile;
    file_put_contents($dataFile, json_encode($menu, JSON_PRETTY_PRINT));
}

$method = $_SERVER['REQUEST_METHOD'];

if ($method === 'GET') {
    $menu = getMenu();
    echo json_encode($menu);
} elseif ($method === 'POST') {
    $input = json_decode(file_get_contents('php://input'), true);

    if (!$input) {
        http_response_code(400);
        echo json_encode(['error' => 'Invalid input']);
        exit;
    }

    $menu = getMenu();

    // Check for delete action
    if (isset($input['action']) && $input['action'] === 'delete' && isset($input['id'])) {
        $updatedMenu = array_filter($menu, function ($item) use ($input) {
            return $item['id'] !== $input['id'];
        });
        saveMenu(array_values($updatedMenu)); // Re-index array
        echo json_encode(['success' => true]);
        exit;
    }

    // Create or Update
    if (isset($input['id']) && !empty($input['id'])) {
        // Update existing
        $found = false;
        foreach ($menu as &$item) {
            if ($item['id'] === $input['id']) {
                $item = array_merge($item, $input);
                $found = true;
                break;
            }
        }
        if (!$found) {
            // If ID provided but not found, treat as new (or error? let's treat as new if we want, but usually update implies existing. 
            // For simplicity, if ID is passed but not found, we append it. But usually ID is generated by backend for new items.
            // Let's assume if ID is passed, it's an update. If not found, error.
            // Actually, for "Add", the frontend might not send ID, or send empty ID.
            http_response_code(404);
            echo json_encode(['error' => 'Item not found']);
            exit;
        }
    } else {
        // Create new
        $newItem = $input;
        $newItem['id'] = uniqid('item_');
        $menu[] = $newItem;
    }

    saveMenu($menu);
    echo json_encode(['success' => true]);
}
?>